language: android
install: true
script: gradle clean assembleDebug

android:
  components:
    - tools
    - build-tools-28.0.3
    - extra
    - android-27

jdk:
  - oraclejdk8

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

before_install:
  # Gradle
  - echo y | android update sdk --no-ui --all --filter "tools"
  - echo y | android update sdk --no-ui --all --filter "build-tools-28.0.3"
  - wget http://services.gradle.org/distributions/gradle-4.10.3-bin.zip
  - unzip gradle-4.10.3-bin.zip
  - export GRADLE_HOME=$PWD/gradle-4.10.3
  - export PATH=$GRADLE_HOME/bin:$PATH

after_success: ./merge_to_dev.sh

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    # Android SDK
    - $HOME/android-sdk-dl
    - $HOME/android-sdk
    # Gradle dependencies
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    # Android build cache (see http://tools.android.com/tech-docs/build-cache)
    - $HOME/.android/build-cache
